# This is a basic workflow to help you get started with Actions

name: deploy
on:
  push
jobs:
  build:
    runs-on: ubuntu-latest # 我们选择使用最新的ubuntu系统
    steps:
      # Checks-out
      - name: checkout
        uses: actions/checkout@v2
      
      # install
      - name: install
        run: | # 执行的命令
          npm install
          npm run build

      # build
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.2 
        with:
          branch: gh-pages # 存放产物的分支名称
          token: ${{ secrets.ACCESS_TOKEN }} # 使用刚新建的secret
          folder: dist # 存放build后产物的目录
          
        
     
